In [16]:
import pandas as pd

import pickle

from itertools import chain

In [19]:
class_names = [['beaver', 'dolphin', 'otter', 'seal', 'whale'],
                        ['aquarium_fish', 'flatfish', 'ray', 'shark', 'trout'],
                        ['orchid', 'poppy', 'rose', 'sunflower', 'tulip'],
                        ['bottle', 'bowl', 'can', 'cup', 'plate'],
                        ['apple', 'mushroom', 'orange', 'pear', 'sweet_pepper'],
                        ['clock', 'keyboard', 'lamp', 'telephone', 'television'],
                        ['bed', 'chair', 'couch', 'table', 'wardrobe'],
                        ['bee', 'beetle', 'butterfly', 'caterpillar', 'cockroach'],
                        ['bear', 'leopard', 'lion', 'tiger', 'wolf'],
                        ['bridge', 'castle', 'house', 'road', 'skyscraper'],
                        ['cloud', 'forest', 'mountain', 'plain', 'sea'],
                        ['camel', 'cattle', 'chimpanzee', 'elephant', 'kangaroo'],
                        ['fox', 'porcupine', 'possum', 'raccoon', 'skunk'],
                        ['crab', 'lobster', 'snail', 'spider', 'worm'],
                        ['baby', 'boy', 'girl', 'man', 'woman'],
                        ['crocodile', 'dinosaur', 'lizard', 'snake', 'turtle'],
                        ['hamster', 'mouse', 'rabbit', 'shrew', 'squirrel'],
                        ['maple_tree', 'oak_tree', 'palm_tree', 'pine_tree', 'willow_tree'],
                        ['bicycle', 'bus', 'motorcycle', 'pickup_truck', 'train'],
                        ['lawn_mower', 'rocket', 'streetcar', 'tank', 'tractor']]

class_names  = list(chain(*class_names))
class_names

['beaver',
 'dolphin',
 'otter',
 'seal',
 'whale',
 'aquarium_fish',
 'flatfish',
 'ray',
 'shark',
 'trout',
 'orchid',
 'poppy',
 'rose',
 'sunflower',
 'tulip',
 'bottle',
 'bowl',
 'can',
 'cup',
 'plate',
 'apple',
 'mushroom',
 'orange',
 'pear',
 'sweet_pepper',
 'clock',
 'keyboard',
 'lamp',
 'telephone',
 'television',
 'bed',
 'chair',
 'couch',
 'table',
 'wardrobe',
 'bee',
 'beetle',
 'butterfly',
 'caterpillar',
 'cockroach',
 'bear',
 'leopard',
 'lion',
 'tiger',
 'wolf',
 'bridge',
 'castle',
 'house',
 'road',
 'skyscraper',
 'cloud',
 'forest',
 'mountain',
 'plain',
 'sea',
 'camel',
 'cattle',
 'chimpanzee',
 'elephant',
 'kangaroo',
 'fox',
 'porcupine',
 'possum',
 'raccoon',
 'skunk',
 'crab',
 'lobster',
 'snail',
 'spider',
 'worm',
 'baby',
 'boy',
 'girl',
 'man',
 'woman',
 'crocodile',
 'dinosaur',
 'lizard',
 'snake',
 'turtle',
 'hamster',
 'mouse',
 'rabbit',
 'shrew',
 'squirrel',
 'maple_tree',
 'oak_tree',
 'palm_tree',
 'pine_tree',
 'willow_tree',
 'bicycle',
 'bus',
 'motorcycle',
 'pickup_truck',
 'train',
 'lawn_mower',
 'rocket',
 'streetcar',
 'tank',
 'tractor']

In [22]:
super_classes = """
aquatic_mammals
fish
flowers
food_containers
fruit_and_vegetables
household_electrical_devices
household_furniture
insects
large_carnivores
large_man-made_outdoor_things
large_natural_outdoor_scenes
large_omnivores_and_herbivores
medium-sized_mammals
non-insect_invertebrates
people
reptiles
small_mammals
trees
vehicles_1
vehicles_2
""".strip().split("\n")

super_classes, len(super_classes)

(['aquatic_mammals',
  'fish',
  'flowers',
  'food_containers',
  'fruit_and_vegetables',
  'household_electrical_devices',
  'household_furniture',
  'insects',
  'large_carnivores',
  'large_man-made_outdoor_things',
  'large_natural_outdoor_scenes',
  'large_omnivores_and_herbivores',
  'medium-sized_mammals',
  'non-insect_invertebrates',
  'people',
  'reptiles',
  'small_mammals',
  'trees',
  'vehicles_1',
  'vehicles_2'],
 20)

In [34]:
def ano():
    
    with open("../../datasets/cifar100/cifar-100-python/meta", "rb") as fh:
        data = pickle.load(fh)
        
    return data["file_label_names"]
ano()

{'fine_label_names': ['apple',
  'aquarium_fish',
  'baby',
  'bear',
  'beaver',
  'bed',
  'bee',
  'beetle',
  'bicycle',
  'bottle',
  'bowl',
  'boy',
  'bridge',
  'bus',
  'butterfly',
  'camel',
  'can',
  'castle',
  'caterpillar',
  'cattle',
  'chair',
  'chimpanzee',
  'clock',
  'cloud',
  'cockroach',
  'couch',
  'crab',
  'crocodile',
  'cup',
  'dinosaur',
  'dolphin',
  'elephant',
  'flatfish',
  'forest',
  'fox',
  'girl',
  'hamster',
  'house',
  'kangaroo',
  'keyboard',
  'lamp',
  'lawn_mower',
  'leopard',
  'lion',
  'lizard',
  'lobster',
  'man',
  'maple_tree',
  'motorcycle',
  'mountain',
  'mouse',
  'mushroom',
  'oak_tree',
  'orange',
  'orchid',
  'otter',
  'palm_tree',
  'pear',
  'pickup_truck',
  'pine_tree',
  'plain',
  'plate',
  'poppy',
  'porcupine',
  'possum',
  'rabbit',
  'raccoon',
  'ray',
  'road',
  'rocket',
  'rose',
  'sea',
  'seal',
  'shark',
  'shrew',
  'skunk',
  'skyscraper',
  'snail',
  'snake',
  'spider',
  'squirrel',
  'streetcar',
  'sunflower',
  'sweet_pepper',
  'table',
  'tank',
  'telephone',
  'television',
  'tiger',
  'tractor',
  'train',
  'trout',
  'tulip',
  'turtle',
  'wardrobe',
  'whale',
  'willow_tree',
  'wolf',
  'woman',
  'worm'],
 'coarse_label_names': ['aquatic_mammals',
  'fish',
  'flowers',
  'food_containers',
  'fruit_and_vegetables',
  'household_electrical_devices',
  'household_furniture',
  'insects',
  'large_carnivores',
  'large_man-made_outdoor_things',
  'large_natural_outdoor_scenes',
  'large_omnivores_and_herbivores',
  'medium_mammals',
  'non-insect_invertebrates',
  'people',
  'reptiles',
  'small_mammals',
  'trees',
  'vehicles_1',
  'vehicles_2']}

In [45]:
def ano():
    
    
    with open("../../datasets/cifar100/cifar-100-python/meta", "rb") as fh:
        meta = pickle.load(fh)
        
    with open("../../datasets/cifar100/cifar-100-python/train", "rb") as fh:
        data = pickle.load(fh, encoding='latin1')
        fine_labels = data["fine_labels"]
        coarse_labels = data["coarse_labels"]
    arr_rows = []
    for fine_label, coarse_label in set(zip(fine_labels, coarse_labels)):
        arr_rows.append(dict(
            coarse_label_name=meta["coarse_label_names"][coarse_label].replace("-", "_"),
            fine_label_name=meta["fine_label_names"][fine_label].replace("-", "_"),
            fine_label=fine_label,
            coarse_label=coarse_label,
        ))
    return pd.DataFrame(arr_rows)
df = ano()

In [46]:
df[df.fine_label_name == "girl"]

   coarse_label_name fine_label_name  fine_label  coarse_label
28            people            girl          35            14

In [47]:
df[df.fine_label.isin([35, 98])]

   coarse_label_name fine_label_name  fine_label  coarse_label
15            people           woman          98            14
28            people            girl          35            14

In [49]:
df.to_csv(
    "../../xaikd/resources/cifar100-label-mapping.csv",
    index=False
)